### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by calderaricaio** [active9/screencap#6]
Hi! I Installed Ffmpeg using Brew then instaled screencap via npm.
Runned the command on the terminal. screencap 5 screen_capture.mp4

Got this error:

ERROR: Error: ffmpeg exited with code 1: video=0: Input/output error

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/screencap/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

Why?

**Comment by goelrohan6** [comment]
Getting the same error

**Comment by active9** [comment]
It would seem this bug is related to fluent-ffmpeg and not screencap.

With that said what version of ffmpeg are you using currently?
What version of node are you using?

Node 15x & FFMPEG Version 4.2.3 with the following configuration is working on Windows 10.

```
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
```

You can check your version of ffmpeg and codec's available by typing > ffmpeg --version and paste your results here.

A possible solution could be to install the exact same version of ffmpeg and testing if the same error occurs.
